# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'Feet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Feet
  pod 'SnapKit', '~> 3.0.2'
  pod 'Zhugeio'
  pod 'Alamofire', '~> 4.2.0'
  pod 'SDWebImage'
  pod 'BaiduMapKit'
  pod 'SwiftyJSON'
#  pod 'RealmSwift'
  pod 'Qiniu'
  pod 'UMengSocialCOM'
  pod 'SVProgressHUD'
  pod 'MJRefresh'
  pod 'Then', '~> 2.1'
  target 'FeetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FeetUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
